  ethstats:
    image: buythewhale/ethstats
    volumes:
      - ./ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3000
  nginx-ethstats:
    image: nginx:1.13.8-alpine
    container_name: nginx-ethstats
    restart: always
    command: /bin/sh -c "envsubst '$$SSL_DOMAIN $$IPFS_SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g                                                                                          'daemon off;'"
    environment:
      - SSL_DOMAIN=evan.network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/ssl:/ssl
      - ./nginx-config/nginx.conf.template:/etc/nginx/nginx.conf.template

